#!/bin/bash

set -x


# Function to create directories if they don't exist
create_directories() {
    if [ ! -d "/Applications" ]; then
        echo "Creating directory: /Applications"
        mkdir /Applications
    else
        echo "Directory already exists: /Applications"
    fi
}

# Check and create directories if necessary
create_directories

# Set User-Agent header
user_agent="BrightSign/8.2.55.5 (XT1144) Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.3 Chrome/69.0.3497.128 Safari/537.36"

# Function to download and installan AppImage
download_appimage() {
    local name="$1"
    local url="$2"
    local destination="/Applications/$name"

    axel -a -q -k -U "$user_agent" -n 8 "$url" -o "$destination"
    chmod +x "$destination"
}

# Download and install agenda
# download_appimage "agenda" " "
# mv /Applications/agenda-* /Applications/agenda

# Download and install arca
# download_appimage "arca" " "
# mv /Applications/arca-* /Applications/arca

# Download and install bonsai
download_appimage "bonsai" "https://download.kde.org/stable/maui/bonsai/1.1.3/bonsai-stable-v1.1.3-git+2cfadec-amd64.AppImage"
mv /Applications/bonsai-* /Applications/bonsai

# Download and install buho
download_appimage "buho" "https://download.kde.org/stable/maui/buho/3.1.0/buho-stable-v3.1.0-git+d1a4550-amd64.AppImage"
mv /Applications/buho-* /Applications/buho

# Download and install clip
download_appimage "clip" "https://download.kde.org/stable/maui/clip/3.1.0/clip-stable-v3.1.0-git+fdb401c-amd64.AppImage"
mv /Applications/clip-* /Applications/clip

# Download and install communicator
# download_appimage "communicator" " "
# mv /Applications/communicator-* /Applications/communicator

# # Download and install fiery
# download_appimage "fiery" " "
# mv /Applications/fiery-* /Applications/fiery

# Download and install index
download_appimage "index" "https://download.kde.org/stable/maui/index/3.1.0/index-stable-v3.1.0-git+f960148-amd64.AppImage"
mv /Applications/index-* /Applications/index

# Download and install nx-software-center
download_appimage "nx-software-center" "https://github.com/Nitrux/nx-software-center/releases/download/latest/nx-software-center-latest-x86_64.AppImage"
mv /Applications/nx-software-center-* /Applications/nx-software-center

# Download and install nota
download_appimage "nota" "https://download.kde.org/stable/maui/nota/3.1.0/nota-stable-v3.1.0-git+019f694-amd64.AppImage"
mv /Applications/nota-* /Applications/nota

# Download and install pix
download_appimage "pix" "https://download.kde.org/stable/maui/pix/3.1.0/pix-stable-v3.1.0-git+33c6c86-amd64.AppImage"
mv /Applications/pix-* /Applications/pix

# Download and install shelf
download_appimage "shelf" "https://download.kde.org/stable/maui/shelf/3.1.0/shelf-stable-v3.1.0-git+e153041-amd64.AppImage"
mv /Applications/shelf-* /Applications/shelf

# Download and install station
download_appimage "station" "https://download.kde.org/stable/maui/station/3.1.0/station-stable-v3.1.0-git+4a7e5c0-amd64.AppImage"
mv /Applications/station-* /Applications/station

# Download and install strike
download_appimage "strike" "https://download.kde.org/stable/maui/strike/1.1.3/strike-stable-v1.1.3-git+c05b1dc-amd64.AppImage"
mv /Applications/strike-* /Applications/strike

# Download and install vvave
download_appimage "vvave" "https://download.kde.org/stable/maui/vvave/3.1.0/vvave-stable-v3.1.0-git+8147565-amd64.AppImage"
mv /Applications/vvave-* /Applications/vvave

