#! /bin/bash

set -x


#	add add AppImages.

{
	printf "%s %s\n" \
		buho				"https://download.kde.org/stable/maui/buho/1.2.2/buho-stable-v1.2.2-amd64.AppImage" \
		clip				"https://download.kde.org/stable/maui/clip/1.1.1/clip-stable-v1.1.1-amd64.AppImage" \
		communicator		"https://download.kde.org/stable/maui/communicator/1.2.1/communicator-v1.2.1-amd64.AppImage" \
		index				"https://download.kde.org/stable/maui/index/1.2.2/index-stable-v1.2.2-amd64.AppImage" \
		nota				"https://download.kde.org/stable/maui/nota/1.2.2/nota-stable-v1.2.2-amd64.AppImage" \
		pix					"https://download.kde.org/stable/maui/pix/1.2.2/pix-stable-v1.2.2-amd64.AppImage" \
		shelf				"https://download.kde.org/stable/maui/shelf/1.1.1/shelf-stable-v1.1.1-amd64.AppImage" \
		station				"https://download.kde.org/stable/maui/station/1.2.2/station-stable-v1.2.2-amd64.AppImage" \
		vvave				"https://download.kde.org/stable/maui/vvave/1.2.2/vvave-stable-v1.2.2-amd64.AppImage"
} | {
	while read name url; do
		axel -a -n 2 -q -k -U "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36" "$url" -o /Applications/$name
	done
}

chmod +x /Applications/*
